FROM exfi/leviathan-tools:core

#####################################################################

ARG WORKDIR=/opt/apps
WORKDIR ${WORKDIR}

#####################################################################

#### Pulumi ####
# Install pulumi plugins
# RUN pulumi plugin install resource random 2.1.2
# RUN pulumi plugin install resource tls 2.1.2
# RUN pulumi plugin install resource kubernetes 2.2.2
# RUN pulumi plugin install resource terraform 2.2.0

#####################################################################

#### AWS ####
# Install awscli
ARG AWS_VERSION
RUN pip3 --no-cache-dir install awscli

# https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html
ARG AWS_IAM_AUTH_VERSION_URL=https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator

# Install aws-iam-authenticator (latest version)
RUN curl --silent -LO ${AWS_IAM_AUTH_VERSION_URL} && \
    mv aws-iam-authenticator ${WORKDIR}/bin/aws-iam-authenticator && \
    chmod +x ${WORKDIR}/bin/aws-iam-authenticator

# Install eksctl (latest version)
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && \
    mv /tmp/eksctl ${WORKDIR}/bin && \
    chmod +x ${WORKDIR}/bin/eksctl

# Install pulumi plugin
# RUN pulumi plugin install resource aws 2.6.1

#####################################################################

#### GCP ####
# Install gcloud-cli
ARG CLOUD_SDK_VERSION=293.0.0
# ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV CLOUDSDK_PYTHON=python3
ENV PATH $PATH:${WORKDIR}/google-cloud-sdk/bin
# RUN curl -sSL https://sdk.cloud.google.com | bash
RUN apt-get -qqy update && apt-get install -qqy \
        curl \
        gcc \
        python3-dev \
        python3-pip \
        apt-transport-https \
        lsb-release \
        openssh-client \
        git \
        make \
        gnupg && \
    pip3 install -U crcmod
RUN curl --silent -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version
# RUN git config --system credential.'https://source.developers.google.com'.helper gcloud.sh
# VOLUME ["/root/.config"]

# Install pulumi plugin
# RUN pulumi plugin install resource gcp 3.6.0

#####################################################################

#### Azure ####
# Install azure-cli
ARG AZURE_VERSION
# RUN curl -L https://aka.ms/InstallAzureCli | bash
RUN pip3 --no-cache-dir install azure-cli

# Install pulumi plugin
# RUN pulumi plugin install resource azure 3.5.1

#####################################################################

#### Rancher ####
ARG RANCHER_VERSION=2.4.3

RUN curl --silent --location "https://github.com/rancher/cli/releases/download/v${RANCHER_VERSION}/rancher-linux-amd64-v${RANCHER_VERSION}.tar.gz" | tar xz -C /tmp && \
    mv /tmp/rancher-v${RANCHER_VERSION} ${WORKDIR}/bin && \
    chmod +x ${WORKDIR}/bin/rancher

# Install pulumi plugin
# RUN pulumi plugin install resource rancher2 2.1.1
# RUN pulumi plugin install resource rke 2.0.0 --server https://github.com/jaxxstorm/pulumi-rke/releases/download/v2.0.0

#####################################################################

# Copy Scripts

#####################################################################

WORKDIR /apps

#####################################################################