FROM exfi/leviathan-tools:core

#####################################################################

ARG WORKDIR=/opt/apps
WORKDIR ${WORKDIR}

#####################################################################

#### Azure ####
# Install azure-cli
ARG AZURE_VERSION
# RUN curl -L https://aka.ms/InstallAzureCli | bash
RUN pip3 --no-cache-dir install azure-cli

#####################################################################

#### Pulumi ####
# RUN pulumi plugin install resource azure 3.5.1

#####################################################################

WORKDIR /apps

#####################################################################
