FROM exfi/leviathan-tools:core

#####################################################################

ARG WORKDIR=/opt/apps
WORKDIR ${WORKDIR}

#####################################################################

#### AWS ####
# Install awscli
ARG AWS_VERSION
RUN pip3 --no-cache-dir install awscli

# https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html
ARG AWS_IAM_AUTH_VERSION_URL=https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator

# Install aws-iam-authenticator (latest version)
RUN curl --silent -LO ${AWS_IAM_AUTH_VERSION_URL} && \
    mv aws-iam-authenticator ${WORKDIR}/bin/aws-iam-authenticator && \
    chmod +x ${WORKDIR}/bin/aws-iam-authenticator

# Install eksctl (latest version)
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && \
    mv /tmp/eksctl ${WORKDIR}/bin && \
    chmod +x ${WORKDIR}/bin/eksctl

#####################################################################

#### Pulumi ####
# Install pulumi plugins
# RUN pulumi plugin install resource aws 2.5.0

#####################################################################

WORKDIR /apps

#####################################################################
